apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ include "judge-engine.fullname" . }}-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "judge-engine.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: {{ .Values.frontend.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "judge-engine.labels" . | nindent 8 }}
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ printf "%s:%s" .Values.frontend.image .Values.version }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: {{ include "judge-engine.fullname" . }}-config
            - secretRef:
                name: {{ include "judge-engine.fullname" . }}-secret

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "judge-engine.fullname" . }}-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "judge-engine.labels" . | nindent 4 }}
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

