{{- if .Values.judgeDb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "judge-engine.fullname" . }}-db
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "judge-engine.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "judge-engine.fullname" . }}-db
  selector:
    matchLabels:
      app: judge-db
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "judge-engine.labels" . | nindent 8 }}
        app: judge-db
    spec:
      containers:
        - name: judge-db
          image: {{ .Values.judgeDb.image }}
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: {{ include "judge-engine.fullname" . }}-config
            - secretRef:
                name: {{ include "judge-engine.fullname" . }}-secret
          volumeMounts:
            - name: judge-db-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: judge-db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.judgeDb.storage }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "judge-engine.fullname" . }}-db
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "judge-engine.labels" . | nindent 4 }}
spec:
  selector:
    app: judge-db
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
{{- end }}
