apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "judge-engine.fullname" . }}-rabbitmq
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "judge-engine.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "judge-engine.fullname" . }}-rabbitmq
  selector:
    matchLabels:
      app: rabbitmq
  replicas: {{ .Values.rabbitmq.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "judge-engine.labels" . | nindent 8 }}
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image }}
          ports:
            - containerPort: 5672
            - containerPort: 15672
          envFrom:
            - configMapRef:
                name: {{ include "judge-engine.fullname" . }}-config
            - secretRef:
                name: {{ include "judge-engine.fullname" . }}-secret
          volumeMounts:
            - name: rabbitmq-storage
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.rabbitmq.storage }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "judge-engine.fullname" . }}-rabbitmq
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "judge-engine.labels" . | nindent 4 }}
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      name: amqp
      targetPort: 5672
    - port: 15672
      name: management
      targetPort: 15672
  clusterIP: None

