apiVersion: v1
kind: Secret
metadata:
  name: {{ include "judge-engine.fullname" . }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "judge-engine.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.judgeDb.user }}
  POSTGRES_PASSWORD: {{ .Values.judgeDb.password }}
  RABBITMQ_USER: {{ .Values.rabbitmq.user }}
  RABBITMQ_PASS: {{ .Values.rabbitmq.password }}