{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "judge-engine.fullname" . }}-sa
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "judge-engine.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.iamRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.iamRoleArn }}
  {{- end }}
{{- end }}
