apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api-gateway
  namespace: judge-engine
  labels:
    app: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: judge-engine-config
            - secretRef:
                name: judge-engine-secret

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: judge-engine
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP

